### ISSUE TITLE
task-based sorting disappeared

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/switchboard#10]
in the UI remake branch (as currently deployed at https://switchboard.clarin-dev.eu/) the task-based sorting (in the tool inventory and the file-dependent tool list) is missing. Please ignore if that's just something that still needs to be implemented.

In any case such a task-based view is important to guide users through the long list of tools that sometimes have a cryptic name.

**Comment by emanueldima** [comment]
Solved in the latest version of the uiremake branch.
