### ISSUE TITLE
Handle not resolved properly

### ISSUE THREAD

**Issue by zinn-claus** [clarin-eric/switchboard#109]
The handle

http://hdl.handle.net/11022/0000-0007-CFD8-D@full_text.txt

is not properly resolved by the switchboard. 
Get the popup error:

Unexpected HTTP status code from resource.

http://hdl.handle.net/11022/0000-0007-CFD8-D@full_text.txt

Please try downloading the resource manually and then uploading it into the Switchboard.

**Comment by emanueldima** [comment]
caused by a HTTP 307 redirect, which is not handled by the switchboard just yet

**Comment by andmor-** [comment]
Can this be fixed already for 2.2.1? (I'm assuming it is easy to solve)

**Comment by emanueldima** [comment]
can be already tested on https://switchboard.clarin-dev.eu/switchboard-test/

**Comment by zinn-claus** [comment]
Thanks for the quick fix!

**Comment by andmor-** [comment]
Fix moved to beta version with v2.2.1-RC3. See: 
https://beta-switchboard.clarin.eu/
