### ISSUE TITLE
Language list is not sorted alphabetically

### ISSUE THREAD

**Issue by proycon** [clarin-eric/switchboard#148]
Minor issue that got me confused for a bit, the language selection list after uploading a file seems sorted alphabetically for a large part but it isn't actually.

**Comment by emanueldima** [comment]
Addressed in https://github.com/clarin-eric/switchboard/pull/140/commits/c4bbb828efb364f1af3fccdb2f091669ef88cc62.
We'll close the issue when the commit gets into master.

**Comment by emanueldima** [comment]
Should be in production now, in 2.2.3
