### ISSUE TITLE
Unclear why the content is not available

### ISSUE THREAD

**Issue by andmor-** [clarin-eric/switchboard#177]
![Screen Shot 2021-01-12 at 18 19 19](https://user-images.githubusercontent.com/6597509/104349225-f1cd6f00-5502-11eb-9099-1e2cf1b564f0.png)

The label "Content is not available" should provide a brief explanation about what's wrong as I don't know why. Maybe on mouse hover or click.

URL to reproduce: 
https://beta-switchboard.clarin.eu/#/vlo/https%3A%2F%2Fclarinws.informatik.uni-leipzig.de%2Fclarinwebservices%2Fsentences%2F11022%2F0000-0000-20E3-B%2Fsentencestext%2F/text%2Fplain/deu

**Comment by emanueldima** [comment]
This has been solved when we separated the dictionary / reference tools from the other ones. This bug does not reproduce now.
