### ISSUE TITLE
udpipe cannot use b2drop input link

### ISSUE THREAD

**Issue by emanueldima** [clarin-eric/switchboard#2]
Steps to reproduce:
1. go to b2drop, create english text file, make it public
2. open switchboard for this file from the context menu  (the one with three dots)
3. show tools in switchboard, choose udpipe, start the tool
4. udpipe does not retrieve the input file as it should. 

This seems to be a cors issue, as udpipe downloads the input file on the frontend (the browser) and the input link sent by switchboard 2.0.0 is the original b2drop link. 

Tentative solution: just send the switchboard link to all the tools, as we can guarantee the accessibility of the data.

**Comment by dietervu** [comment]
keeping original reporter @kosarko in the loop of this issue

**Comment by emanueldima** [comment]
solved in 2.1.0, just pushed in production
