### ISSUE TITLE
Responsive front end design

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/switchboard#21]
Implement a responsive design using the basic [bootstrap grid layout](https://getbootstrap.com/docs/3.3/css/) to replace current table layout and allow for dynamic flowing of page components to make the page usable on less wide screens.

**Comment by emanueldima** [comment]
The new revamped UI (uiremake branch) solves this, but let’s wait until it’s deployed.

**Comment by emanueldima** [comment]
solved on 2.1.0
