### ISSUE TITLE
Investigate off-the-shelf upload and cloud connect widgets

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/switchboard#26]
There are some nice off-the-shelf solutions available like http://cloud-explorer.org/ (open source) or https://www.filestack.com/features/file-uploader (commercial, cloud service) – might be good to take a look as inpiration or possible as replacement for an own implementation.

**Comment by emanueldima** [comment]
We now have our own backend storage code which is just a few hundreds of lines of code, easy to change and configurable. Close?

**Comment by emanueldima** [comment]
I think this issue is no longer valid, closing it.
