### ISSUE TITLE
have app metadata to define the status of the app

### ISSUE THREAD

**Issue by claus-zinn** [clarin-eric/switchboard#30]
check whether app metadata should get a status tag such as 'production', 'development'. Users can then ask the LRS to only list tools with a given status, e.g., only stable tools, include experimental tools.

**Comment by emanueldima** [comment]
It looks this has been long implemented, see for example https://github.com/clarin-eric/switchboard-tool-registry/blob/master/Alpino.json: “deployment” key. Close?
