### ISSUE TITLE
Tool call API adds mimetype to calling URL

### ISSUE THREAD

**Issue by fungunga** [clarin-eric/switchboard#313]
If I call switchboard using

<https://switchboard.clarin.eu/#/dhrep/https%3A%2F%2Frepository.de.dariah.eu%2F1.0%2Fdhcrud%2Fhdl:21.11113%2F0000-000F-746E-4%2Fdata/application%2Foctet-stream>,

or

<https://switchboard.clarin.eu/#/dhrep/https%3A%2F%2Frepository.de.dariah.eu%2F1.0%2Fdhcrud%2Fhdl:21.11113%2F0000-000F-746E-4>,

or (if mimetype is correctly set)

<https://switchboard.clarin.eu/#/dhrep/https%3A%2F%2Frepository.de.dariah.eu%2F1.0%2Fdhcrud%2Fhdl:21.11113%2F0000-000F-746E-4%2Fdata/application%252Fvnd.google-earth.kml%252Bxml>,

I always get as tool call URL like

<https://geobrowser.de.dariah.eu/?kml=https%3A%2F%2Fswitchboard.clarin.eu%2Fapi%2Fstorage%2F34a922c8-4adc-4dd5-9a2d-9a78f6e3acbe%3Fmediatype%3Dapplication%252Fvnd.google-earth.kml%252Bxml>

Geo-Browser seems not to be able to cope with the mediatype path param, has the tool to cope with the mediatype parameter? Can it be avoided to be appended to the URL by Switchboard?

**Comment by andmor-** [comment]
Indeed "mediatype" seems to be added unilaterally.
Although if I remove it, I get:
[https://geobrowser.de.dariah.eu/?kml=https%3A%2F%2Fswitchboard.clarin.eu%2Fapi%2Fstorage%2F34a922c8-4adc-4dd5-9a2d-9a78f6e3acbe](https://geobrowser.de.dariah.eu/?kml=https%3A%2F%2Fswitchboard.clarin.eu%2Fapi%2Fstorage%2F34a922c8-4adc-4dd5-9a2d-9a78f6e3acbe) 
Which still leads to an error (parsing) in https://geobrowser.de.dariah.eu

**Comment by fungunga** [comment]
Hm, for me <https://geobrowser.de.dariah.eu/?kml=https%3A%2F%2Fswitchboard.clarin.eu%2Fapi%2Fstorage%2F8198c709-5b02-458f-82b2-4ce3288b5c87%3Fmediatype%3Dapplication%252Fvnd.google-earth.kml%252Bxml> doesn't work, but <https://geobrowser.de.dariah.eu/?kml=https%3A%2F%2Fswitchboard.clarin.eu%2Fapi%2Fstorage%2F8198c709-5b02-458f-82b2-4ce3288b5c87> does.

**Comment by andmor-** [comment]
I can reproduce the issue. We are taking a look at the Switchboard side but I believe the Geobrowser should also be able to cope with unused parameters.  We will keep this issue updated with the developments on the Switchboard side.

**Comment by fungunga** [comment]
Thanks, very good! See <https://gitlab.gwdg.de/dariah-de/geo-browser/-/issues/98>

**Comment by fungunga** [comment]
Hmmmmm, <https://switchboard.clarin.eu/api/storage/e2621486-77c8-4b78-8009-e742972a3f0d?mediatype=application%2Fvnd.google-earth.kml%2Bxml> does indeed deliver an KML file. Maybe Geo-Browser loads files incorrectly?

**Comment by andmor-** [comment]
Indeed the Switchboard assumes that (in your example): "https://switchboard.clarin.eu/api/storage/e2621486-77c8-4b78-8009-e742972a3f0d?mediatype=application%2Fvnd.google-earth.kml%2Bxml" is treated by the receiving tool as the full URL were to fetch the resource from. This is working as the Switchboard is passing only a single query parameter (`kml` in your example) to the Geobrowser. Note the escaping:

https://geobrowser.de.dariah.eu/?kml=https%3A%2F%2Fswitchboard.clarin.eu%2Fapi%2Fstorage%2Fe2621486-77c8-4b78-8009-e742972a3f0d%3Fmediatype%3Dapplication%252Fvnd.google-earth.kml%252Bxml

**Comment by andmor-** [comment]
I suspect there is a query parameter parsing error on the side of the Geobrowser

**Comment by fungunga** [comment]
Right, hmpf! You are right! Geo-Browser wants to load <https://switchboard.clarin.eu/api/storage/d859a954-21f7-4ba5…-ed25341df319?mediatype=application/vnd.google-earth.kml+xml>, URL parameters must be (must STAY) URL encoded!

**Comment by andmor-** [comment]
It also seems that the Switchboard is double encoding the `mediatype` value and I can't see an obvious reason for that. Keeping this issue open until we can clarify it.

**Comment by fungunga** [comment]
Shouldn't <https://switchboard.clarin.eu/api/storage/d859a954-21f7-4ba5-8644-ed25341df319?mediatype=application/vnd.google-earth.kml> be working as well?

**Comment by andmor-** [comment]
both work for me. The following 3 URLs return the same file:

https://switchboard.clarin.eu/api/storage/d859a954-21f7-4ba5-8644-ed25341df319?mediatype=application%2Fvnd.google-earth%2Bkml

https://switchboard.clarin.eu/api/storage/d859a954-21f7-4ba5-8644-ed25341df319?mediatype=application/vnd.google-earth.kml

https://switchboard.clarin.eu/api/storage/d859a954-21f7-4ba5-8644-ed25341df319

**Comment by fungunga** [comment]
There is an extra "xml" at the end? <https://geobrowser.de.dariah.eu/?kml=https%3A%2F%2Fswitchboard.clarin.eu%2Fapi%2Fstorage%2Feac2f506-bdf0-4539-aac0-a391ea77c78d%3Fmediatype%3Dapplication%252Fvnd.google-earth.kml%252Bxml>

**Comment by fungunga** [comment]
Without "xml" it works just fine...

**Comment by fungunga** [comment]
Then <https://switchboard.clarin.eu/api/storage/d859a954-21f7-4ba5-8644-ed25341df319?mediatype=application/vnd.google-earth.kml+xml> should work, and not <https://switchboard.clarin.eu/api/storage/d859a954-21f7-4ba5-8644-ed25341df319?mediatype=application/vnd.google-earth.kml>?

**Comment by andmor-** [comment]
According to: https://datatracker.ietf.org/doc/html/rfc3986#section-2.2 what should work (and seems to) is:
https://switchboard.clarin.eu/api/storage/d859a954-21f7-4ba5-8644-ed25341df319?mediatype%3Dapplication%2Fvnd.google-earth.kml%2Bxml

**Comment by fungunga** [comment]
---> to be fixed in Geo-Browser.......
