### ISSUE TITLE
What should the absence of language specification for a tool mean?

### ISSUE THREAD

**Issue by emanueldima** [clarin-eric/switchboard#48]
1. the tool can accept any language
2. the tool cannot accept any language (absurd, but seems to be the current behavior)?

N.B. We don't have any such tools yet, but the question is whether we should accept an empty language spec or not.

**Comment by andmor-** [comment]
Personally I prefer explicit declarations, so if a tool accepts any language, IMO it should have a single value: `any` in its `languages` field. As you say, there is not really a case for `none`, as that is absurd.
So I think we should not accept an empty language spec.

**Comment by emanueldima** [comment]
I agree that it should be explicit, but I don't think using `any` is a good choice, since it can mean other things (https://en.m.wikipedia.org/wiki/Anyin_language). I'd prefer to have a boolean field in a `language` object.

**Comment by andmor-** [comment]
Fair point! 
Regardless of the chosen word, we should use different types to avoid this anyway. Say for a selection of languages we use an array (as it is now), but for the "any language" option, we use a simple value or an object. The code then takes this into account and makes sure the concepts are never confused.

**Comment by emanueldima** [comment]
Ok, I found (while developing a schema for json tool files) that some tools accept 'generic' as an input language. Needless to say, that's not an ISO 639-3 code, but a special case. I temporarily accepted it as a description for tools that don't depend on language (PR #51) but I do plan to change it in the next tools specification version.

**Comment by emanueldima** [comment]
closing this, as it's now a subitem of #4
