### ISSUE TITLE
Correctly detect TEI format (with variants)

### ISSUE THREAD

**Issue by emanueldima** [clarin-eric/switchboard#5]
Currently we use the Apache Tika library for media type detection. The library does not recognize TEI files and reports their type as just XML.

**Comment by andmor-** [comment]
[FLAT's doorkeeper](url) solves this (e.g. for eaf files: application/x-elan+xml) by doing an xpath analyzes on the report outputted by FITS. See: https://github.com/TLA-FLAT/DoorKeeper/blob/develop/src/main/java/nl/mpi/tla/flat/deposit/action/FITS.java#L82

In their architecture, one can setup xpath assertions in a configuration XML file. These assertions are then tested against the FITS output report. The XML assertions file syntax looks like this:
```
<!-- *** annotation file types *** -->
    <!-- ELAN eaf -->
    <mimetype value="application/x-elan+xml" xpath="//fits:identity/@mimetype='text/xml'">
        <assertions xpath="/fits:fits/fits:fileinfo/fits:filename/replace(., '.*\.', '') = 'eaf'">
            <assert xpath="exists(/fits:fits/fits:metadata/fits:text/fits:markupLanguage[starts-with(., 'http://www.mpi.nl/tools/elan/EAFv')])" message="Your ELAN file [{replace(/fits:fits/fits:fileinfo/fits:filename,$work,'')}] does not contain a valid schema declaration"/>
            <assert xpath="/fits:fits/fits:metadata/fits:text/fits:charset = 'UTF-8'" message="The character encoding of your ELAN file [{replace(/fits:fits/fits:fileinfo/fits:filename,$work,'')}] is [{/fits:fits/fits:metadata/fits:text/fits:charset}], should be UTF-8"/>
            <assert xpath="/fits:fits/fits:filestatus/fits:valid = 'true'" message="Your ELAN file [{replace(/fits:fits/fits:fileinfo/fits:filename,$work,'')}] is not a valid XML file"/>
        </assertions>
    </mimetype>
    
    <!-- Toolbox/Chat: not quite sure yet how to distinguish them from plain text using FITS -->
    
    
    <!-- *** other file types *** -->
    <!-- Generic XML -->
    <mimetype value="text/xml">
        <assertions>
            <assert xpath="/fits:fits/fits:filestatus/fits:valid = 'true'" message="Your file [{replace(/fits:fits/fits:fileinfo/fits:filename,$work,'')}] is not a valid XML file"/>
            <assert xpath="/fits:fits/fits:metadata/fits:text/fits:charset = 'UTF-8'" message="The character encoding of your XML file [{replace(/fits:fits/fits:fileinfo/fits:filename,$work,'')}] is [{/fits:fits/fits:metadata/fits:text/fits:charset}], should be UTF-8"/>
            <assert xpath="/fits:fits/fits:fileinfo/fits:filename/replace(., '.*\.', '') = ('xml')" message="Your file [{replace(/fits:fits/fits:fileinfo/fits:filename,$work,'')}] is an XML file, but has a different file extension than '.xml'"/>
        </assertions>
    </mimetype>
```

Perhaps we could use the same strategy or even the same Java component. (If desired, we could approach the current developers of FLAT to try to generalize this component.)

**Comment by emanueldima** [comment]
As a temporary improvement we could accept the mimetype sent by the vlo (or other repository) if the detected mimetype is XML and the repository provided mimetype is a subset of XML. This will only work with resources coming from a repository, but is still better than the current behavior.

**Comment by dietervu** [comment]
We should in any case have a robust solution that can cope with the official TEI mimetype, "application/tei+xml".

At the moment there is only 1 repository providing this correct mimetype in the metadata, see https://vlo.clarin.eu/record?fqType=format:or&fq=format:application/tei%2Bxml&docId=http_58__47__47_worldviews.gei.de_47_rest_47_content_47_cmdi_47_PT_1929_DeBrito_ResumoHistoriaGeral_122_47_ger_47_ for an example.

The switchboard warning in case of a non-recognized mimetype could also be more detailed (right now it is a combination of potential reasons why it cannot process a file)

**Comment by emanueldima** [comment]
Created new Issue https://github.com/clarin-eric/switchboard/issues/14 with a solution to alleviate the problem. This issue is still valid, but will be fixed at a later time.
