### ISSUE TITLE
Possibility to configure the values in `config.yaml` via environment variables

### ISSUE THREAD

**Issue by andmor-** [clarin-eric/switchboard#50]
Currently, to be able to do both: set the Switchboard configuration via environment variables, and at the same time have defaults, I override the switchboard `config.yaml` with this [one](https://gitlab.com/CLARIN-ERIC/compose_clarin_switchboard/blob/master/clarin/switchboard-config/config.yaml).
I was thinking this could go directly into this repository replacing  [config.yaml](https://github.com/clarin-eric/switchboard/blob/master/backend/config.yaml)

The advantage for the switchboard is: it would allow to generically pass configuration values via environment variables without losing the ability to set defaults.
The disadvantage is: the file becomes much more painful to read!

What do you think?

**Comment by andmor-** [comment]
Perhaps replacing the `APP_` prefix by `LRS_` or something else less generic (as suggested by @twagoo). 
The variable names can also be changed.

**Comment by emanueldima** [comment]
fixed by https://github.com/clarin-eric/switchboard/commit/5064fecb584bf0f315057316a922c80a28ea6ff8
