### ISSUE TITLE
FITS plugin for detecting linguistic media types

### ISSUE THREAD

**Issue by emanueldima** [clarin-eric/switchboard#57]
The plugin should be designed so it's easily updated by third parties with more knowledge in the specific formats we try to detect.

connected to #5

**Comment by emanueldima** [comment]
FITS is too slow. It needs 13-14 seconds to detect that a 232K file is just xml, on a powerful modern computer. I think we should make our own fast detection of the most used media types, and when that fails invoke FITS.

Test details:

- 2017 iMac (4 Core i7, 32GB RAM, 512SSD); 
- 232K TEI file (Shakespeare's Tempest)
- calling fits from the command line as 
  `time ./fits.sh -x -i ~/Downloads/test_switchboard/tempest.xml`

**Comment by emanueldima** [comment]
Seems that a big part of the previous values are slow startup time. Using curl with an already started fits instance running in a docker container the times are down to .4-.5 seconds. I still think it's too much, but a bit more reasonable.

**Comment by proycon** [comment]
I'm glad I heard this during the switchboard workshop today too: having only a mime-type (even once that specifically says ``application/tei+xml`` or ``application/folia+xml``) is very often insufficient and more detailed knowledge about the format is required. FoLiA addresses this issue by explicitly requiring [a metadata block with declarations for all annotation types and used tagsets](https://folia.readthedocs.io/en/latest/metadata.html#annotation-declarations), so all the information regarding what annotation layers are available in a document should be available (without needing to parse the entire document which would be prohibitive on performance as documents of hundreds of megabytes are not uncommon!).

Let me know when the needed arises, I could implement a FITS module (or probably whatever other system) for FoLiA.

**Comment by emanueldima** [comment]
Thank you for the offer, I think this is a very good idea. Now it looks like it's not really a good idea to use FITS, since it's big and slow, so the actual interface is not settled yet, but this should be a minor change once you have a FoLiA profiler.

**Comment by emanueldima** [comment]
I will close this issue now, since the profiler has been released: https://github.com/weblicht/profiler/

@proycon If you would still like to add a FoLiA profiler, this would have to be integrated in the new here: https://github.com/weblicht/profiler/. Let me know if you need any help, the docs are a bit sparse right now.

**Comment by proycon** [comment]
@emanueldima Thanks, I'll take a look at that new project and see what I can do!
