### ISSUE TITLE
Specify encoding of stored files in the content-type header

### ISSUE THREAD

**Issue by emanueldima** [clarin-eric/switchboard#64]
When we download a Switchboard stored file (e.g. https://switchboard.clarin.eu/api/storage/f9a2d822-1b8e-4b8c-9e45-303f70d3f3ef), the HTTP response does not have the information about file encoding in the HTTP header. 

Now the Content-type header is: `Content-Type: text/plain`
and should be: `Content-Type: text/plain; charset=utf-8`

This breaks some tools (e.g. Coreference Resolution Concraft -> Bartek).

**Comment by andmor-** [comment]
Maybe related to [#122 ](https://github.com/clarin-eric/switchboard-tool-registry/issues/102) of switchboard-tool-registry
