### ISSUE TITLE
Bind UI version number to this project's tag numbers

### ISSUE THREAD

**Issue by andmor-** [clarin-eric/switchboard#8]
At the moment the version number for this application is a bit confusing.
We currently have:
- https://github.com/clarin-eric/switchboard/blob/master/webui/package.json#L4 (https://github.com/clarin-eric/switchboard/blob/master/webui/package-lock.json#L3 after locking)
- https://github.com/clarin-eric/switchboard/blob/master/backend/pom.xml#L7

This seems to be visible on the API call page:
https://beta-switchboard.clarin.eu/api/info  there are 3 "version" fields! And at least one of them is detached from the others.
I can't think of a reason not to only have one version number (ideally coming from a created git tag).

Plus when building, we use to define the version number for the docker image here:
https://github.com/clarin-eric/switchboard/blob/master/Makefile#L1

This is not ideal since the image to be used in our deployments is not this one, but the one coming from GitLab. Here we should just use ["latest"](https://github.com/clarin-eric/switchboard/commit/b9d3e535b5d8d33c9227935b168a6f1f4043d66b) as the real image version numbers come from the tags created on GitLab.

It would be great if we can do the same here and use the created tag number to fill in the UI version number at build time. The generated release filename already uses that number (travis variable ${TRAVIS_TAG} which is made available to the environment at build time by travis).

**Comment by emanueldima** [comment]
We have the following places where a version shows up:

- [ ] DOCKERTAG in  ./Makefile
- [ ] version in backend/pom.xml
- [ ] version in webui/package.json
- most recent git tag

**Comment by andmor-** [comment]
Yes. I think it is preferable to only have one version number coming from "most recent git tag". But at least we could bind these vars to each other so we don't have to go around the code when we have a new version.

**Comment by emanueldima** [comment]
We decided (André and I) that we can eliminate the version in package.json, use the git tag for pom.xml, and the latest tag for the docker image
