### ISSUE TITLE
Fill in changelog

### ISSUE THREAD

**Issue by andmor-** [clarin-eric/switchboard#9]
Since we moved to v2 the [changelog](https://github.com/clarin-eric/switchboard/blob/master/Changelog.md) as been neglected. I think it would be nice to keep it up to date.

Alternatively we should remove it.

**Comment by emanueldima** [comment]
@dietervu @andmor- @twagoo  I would remove it, does anybody think it is important?

**Comment by dietervu** [comment]
I think it can be very useful, e.g. when creating news items about new versions or when doing reporting. The good thing is if we keep a changelog file (like the [VLO](https://github.com/clarin-eric/VLO/blob/master/CHANGES.txt) does too) I will not need to bother you all the time to ask which new features are part of a release ;-)
